## Core Data Structures in Pandas
Pandas is built on two main data structures:

Series → One-dimensional (like a single column in Excel).     
DataFrame → Two-dimensional (like a full spreadsheet or SQL table).

In [3]:
import pandas as pd

In [11]:
s = pd.Series([10, 20, 30, 40, 50])

In [12]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [13]:
s1 = pd.Series([45, 78, 98, 65, 53, 75, 85])

In [14]:
type(s1)

pandas.core.series.Series

In [8]:
m

0    45
1    78
2    98
3    65
4    53
5    75
6    85
dtype: int64

In [18]:
s2 = pd.Series([79, 87, 98, 95, 96, 89], index = ["Harry", "Hena", "Addy", "Luffy", "Adam", "Zoro"])

In [19]:
s2

Harry    79
Hena     87
Addy     98
Luffy    95
Adam     96
Zoro     89
dtype: int64

In [20]:
s2["Addy"]

np.int64(98)

In [21]:
s2["Zoro"]

np.int64(89)

In [23]:
data = {
    "name" : ["Adam", "Addy", "Luffy", "Zoro", "Harry"],
    "age" : ["25", "26", "19", "21", "26"],
    "country" : ["Asia", "India", "East_Blue", "West_Blue", "India"],
    "fav_color" : ["Blood_Red", "Blue", "Red", "Green", "Black"]
}

In [24]:
pd.DataFrame(data)

    name age    country  fav_color
0   Adam  25       Asia  Blood_Red
1   Addy  26      India       Blue
2  Luffy  19  East_Blue        Red
3   Zoro  21  West_Blue      Green
4  Harry  26      India      Black

In [25]:
df = pd.DataFrame(data)

In [26]:
df

    name age    country  fav_color
0   Adam  25       Asia  Blood_Red
1   Addy  26      India       Blue
2  Luffy  19  East_Blue        Red
3   Zoro  21  West_Blue      Green
4  Harry  26      India      Black

In [27]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [29]:
df.columns

Index(['name', 'age', 'country', 'fav_color'], dtype='object')