In [26]:
import pandas as pd

In [9]:
data = [['harry', 34], ['luffy', 66], ['zoro', 88], ['ussop', 53], ['sanji', 69]]

In [10]:
data

[['harry', 34], ['luffy', 66], ['zoro', 88], ['ussop', 53], ['sanji', 69]]

In [11]:
pd.DataFrame(data, columns=["Names","Marks"])

   Names  Marks
0  harry     34
1  luffy     66
2   zoro     88
3  ussop     53
4  sanji     69

In [16]:
data = {'A': [2, 4, 3], 'B': [38, 24, 36]}

In [17]:
data

{'A': [2, 4, 3], 'B': [38, 24, 36]}

In [18]:
df = pd.DataFrame(data)

In [19]:
df

   A   B
0  2  38
1  4  24
2  3  36

In [20]:
import numpy as np

In [21]:
arr = np.array([[1, 2], [5, 6]])

In [22]:
df = pd.DataFrame(arr, columns=["A", "B"])

In [23]:
df

   A  B
0  1  2
1  5  6

In [30]:
df = pd.read_excel("data.xlsx.xlsx")

In [31]:
df

       Name School  Marks
0     Luffy     EB     65
1      Zoro     WB     75
2     Sanji     SB     69
3     Ussop     WB     58
4    Franky     NB     62
5    Jinbay     FL     73
6     Brook     NB     67
7      Nami     EB     58
8     Robin     WB     68
9    Yamato     WN     72
10     Vivi     EB     52
11  Chopper     WB     54

In [38]:
z = pd.read_csv("industry.csv")

In [39]:
z

                         Industry
0              Accounting/Finance
1    Advertising/Public Relations
2              Aerospace/Aviation
3   Arts/Entertainment/Publishing
4                      Automotive
5                Banking/Mortgage
6            Business Development
7            Business Opportunity
8         Clerical/Administrative
9         Construction/Facilities
10                 Consumer Goods
11               Customer Service
12             Education/Training
13               Energy/Utilities
14                    Engineering
15            Government/Military
16                          Green
17                     Healthcare
18             Hospitality/Travel
19                Human Resources
20       Installation/Maintenance
21                      Insurance
22                       Internet
23                Job Search Aids
24       Law Enforcement/Security
25                          Legal
26           Management/Executive
27       Manufacturing/Operations
28                      Marketing
29           Non-Profit/Volunteer
30         Pharmaceutical/Biotech
31          Professional Services
32             QA/Quality Control
33                    Real Estate
34        Restaurant/Food Service
35                         Retail
36                          Sales
37               Science/Research
38                  Skilled Labor
39                     Technology
40             Telecommunications
41       Transportation/Logistics
42                          Other

In [53]:
df = pd.read_json("dataxl.json")

In [54]:
df

   name lang
0  Adam   Py
1  Addy   JS

In [55]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [56]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

EDA (Exploratory Data Analysis)
Exploratory Data Analysis (EDA) is an essential first step in any data science project.

It involves taking a deep look at the dataset to understand its structure, spot patterns, identify anomalies, and uncover relationships between variables. This process includes generating summary statistics, checking for missing or duplicate data, and creating visualizations like histograms, box plots, and scatter plots. The goal of EDA is to get a clear picture of what the data is telling you before applying any analysis or machine learning models.

By exploring the data thoroughly, you can make better decisions about how to clean, transform, and model it effectively.

Once your DataFrame is ready, run these to understand your data:

df.head()         # First 5 rows
df.tail()         # Last 5 rows
df.info()         # Column info: types, non-nulls
df.describe()     # Stats for numeric columns
df.columns        # List of column names
df.shape          # (rows, columns)

In [57]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [58]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [60]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [62]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [63]:
df.shape

(244, 7)