### Data selection and filtering

In [10]:
# Selecting columnd
import pandas as pd
df = pd.read_csv("dataa.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [5]:
df['Actor']

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [6]:
df['Actor'][3]

'Ranbir Kapoor'

In [8]:
df[['Actor', 'IMDb']]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [11]:
# Selecting by index
df.loc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [12]:
df.iloc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [13]:
# selecting particular cell
df.loc[8, 'IMDb']

np.float64(7.0)

In [14]:
df.loc[7, 'IMDb']

np.float64(6.5)

In [16]:
df.loc[7, 'Actor']

'Hrithik Roshan'

In [17]:
df.iloc[7, 5]

np.float64(6.5)

In [19]:
df.iloc[7, 0]

'Hrithik Roshan'

In [20]:
df.loc[0:2]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [23]:
df.loc[0:2, ['Actor', 'IMDb', 'Film']]

            Actor  IMDb             Film
0  Shah Rukh Khan   7.2          Pathaan
1     Salman Khan   6.0  Tiger Zinda Hai
2      Aamir Khan   8.4           Dangal

In [24]:
df.iloc[0:2, 0:2]

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

In [27]:
df.at[0, 'Actor']

'Shah Rukh Khan'

In [28]:
df.iat[0,0]

'Shah Rukh Khan'

In [29]:
df[df['IMDb']>7]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [30]:
df[df['IMDb']>7]['Actor']

0         Shah Rukh Khan
2             Aamir Khan
5     Ayushmann Khurrana
6          Rajkummar Rao
11         Vicky Kaushal
Name: Actor, dtype: object

In [32]:
df[df['IMDb']>6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [33]:
df[(df['IMDb']>6) & (df['Year']>2018)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [34]:
df[(df['IMDb']>6) | (df['Year']>2018)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [36]:
df.query('Year > 2019')

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

In [37]:
df.query('Year > 2019 and IMDb > 6')

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [47]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [48]:
result = df.query('200 < `BoxOffice(INR Crore)` <= 600')
print(result)

             Actor                      Film  Year            Genre  \
1      Salman Khan           Tiger Zinda Hai  2017           Action
3    Ranbir Kapoor                Brahmastra  2022          Fantasy
4    Ranveer Singh                 Padmaavat  2018       Historical
7   Hrithik Roshan                       War  2019           Action
8     Akshay Kumar                Good Newwz  2019           Comedy
9    Kartik Aaryan         Bhool Bhulaiyaa 2  2022    Horror Comedy
10    Varun Dhawan     Badrinath Ki Dulhania  2017  Romantic Comedy
11   Vicky Kaushal  Uri: The Surgical Strike  2019           Action

    BoxOffice(INR Crore)  IMDb
1                    565   6.0
3                    431   5.6
4                    585   7.0
7                    475   6.5
8                    318   7.0
9                    266   5.9
10                   201   6.1
11                   342   8.2

In [53]:
df2 = df.loc[0,'Actor'] = 'Furkhan'

In [54]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Furkhan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
Actor,Furkhab,Furkhab,Furkhab,Furkhab,Furkhab,Furkhab

In [67]:
df2 = df.loc[1,'Actor'] = 'Addy'

In [68]:
df2

'Addy'

In [69]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Furkhan,Pathaan,2023,Action,1050,7.2
1,Addy,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
Actor,Furkhab,Furkhab,Furkhab,Furkhab,Furkhab,Furkhab