In [3]:
import pandas as pd

In [4]:
# Sample data frame
data = {
    'Name': ["Alice", "Bob", "Charlie"],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)
df

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

##

In [15]:
# *** Important Melt
df.melt(id_vars=None, value_vars=None, var_name=None, value_name="value", col_level=None)

   variable    value
0      Name    Alice
1      Name      Bob
2      Name  Charlie
3      Math       85
4      Math       78
5      Math       92
6   Science       90
7   Science       82
8   Science       89
9   English       88
10  English       85
11  English       94

In [9]:
df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"], var_name="Subject", value_name="Score")

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

##

In [14]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [17]:
df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"], var_name="Subject", value_name="Score")

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [12]:
# using Pivot() ***
# df.pivot(index="Name", columns="Subject", values="Score")  - gives error if dublicate values are there

In [19]:
#df.pivot_table(index="Name", columns="Subject", values="Score", aggfunc="mean")

## pivot code wasn't executed