In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [5]:
pd.merge(employees, departments, on="DeptID")   #Inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [7]:
pd.merge(employees, departments, on="DeptID", how="left")   # Left join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [8]:
pd.merge(employees, departments, on="DeptID", how="right")   # Right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [10]:
pd.merge(employees, departments, on="DeptID", how="outer")   # Outerjoin

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [12]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

In [13]:
df1

    Name
0  Alice
1    Bob

In [14]:
df2

      Name
0  Charlie
1    David

In [15]:
pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [16]:
pd.concat([df1, df2], axis =1)

    Name     Name
0  Alice  Charlie
1    Bob    David

In [17]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "Score": [423, 634]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "age": [45, 60]})

In [18]:
df1

    Name  Score
0  Alice    423
1    Bob    634

In [19]:
df2

      Name  age
0  Charlie   45
1    David   60

In [20]:
pd.concat([df1, df2])

      Name  Score   age
0    Alice  423.0   NaN
1      Bob  634.0   NaN
0  Charlie    NaN  45.0
1    David    NaN  60.0

In [21]:
pd.concat([df1, df2], axis =1)

    Name  Score     Name  age
0  Alice    423  Charlie   45
1    Bob    634    David   60