Using Beautiful Soup for Data Collection
1. What is BeautifulSoup?
BeautifulSoup is a Python library used to parse HTML and XML documents.
It creates a parse tree from page content, making it easy to extract data.
It is often used with requests to scrape websites.

In [3]:
pip install beautifulsoup4 lxml

Requirement already satisfied: beautifulsoup4 in c:\users\lenovo\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: lxml in c:\users\lenovo\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\lenovo\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from beautifulsoup4) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [11]:
from bs4 import BeautifulSoup
import requests

url = "https://example.com"
response = requests.get(url)

soup = BeautifulSoup(response.text, "lxml")

In [45]:
from bs4 import BeautifulSoup

with open("htmls/page1.html") as f:
    content = f.read()

soup = BeautifulSoup(content, "html.parser")

h3s = soup.find_all("h3")

In [46]:
with open("htmls/page1.html") as f:
    content = f.read()

In [47]:
soup = BeautifulSoup(content, "html.parser")

In [23]:
soup.h1

In [24]:
soup.h1.text

'All products'

In [32]:
soup.find("h3")

In [34]:
h3s = soup.find_all("h3")

In [35]:
h3s

[<h3><a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>,
 <h3><a href="tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>,
 <h3><a href="soumission_998/index.html" title="Soumission">Soumission</a></h3>,
 <h3><a href="sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>,
 <h3><a href="sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>,
 <h3><a href="the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>,
 <h3><a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>,
 <h3><a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>,
 <h3><a href="the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>,
 <h3><a href="the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>,
 <h3><a href="starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>,
 <h3><a href="shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>,
 <h3><a href="set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>,
 <h3><a href="scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>,
 <h3><a href="rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>,
 <h3><a href="our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>,
 <h3><a href="olio_984/index.html" title="Olio">Olio</a></h3>,
 <h3><a href="mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>,
 <h3><a href="libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>,
 <h3><a href="its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>]

In [60]:
for h3 in h3s:
    print(h3.find("a")['title'])

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

In [61]:
from bs4 import BeautifulSoup

with open("htmls/page1.html") as f:
    content = f.read()

soup = BeautifulSoup(content, "html.parser")

h3s = soup.find_all("h3")

In [66]:
articles = soup.select("article.product_pod")

In [67]:
for article in articles:
    title = article.find("h3").find("a")["title"]
    print(title)

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

In [69]:
for article in articles:
    title = article.find("h3").find("a")["title"]
    price = article.select_one("p.price_color").text
    print(price)

Ã‚Â£51.77
Ã‚Â£53.74
Ã‚Â£50.10
Ã‚Â£47.82
Ã‚Â£54.23
Ã‚Â£22.65
Ã‚Â£33.34
Ã‚Â£17.93
Ã‚Â£22.60
Ã‚Â£52.15
Ã‚Â£13.99
Ã‚Â£20.66
Ã‚Â£17.46
Ã‚Â£52.29
Ã‚Â£35.02
Ã‚Â£57.25
Ã‚Â£23.88
Ã‚Â£37.59
Ã‚Â£51.33
Ã‚Â£45.17

In [70]:
for article in articles:
    title = article.find("h3").find("a")["title"]
    price = article.select_one("p.price_color").text.split("£")[1]
    print(price)

51.77
53.74
50.10
47.82
54.23
22.65
33.34
17.93
22.60
52.15
13.99
20.66
17.46
52.29
35.02
57.25
23.88
37.59
51.33
45.17

In [72]:
items = []
for article in articles:
    title = article.find("h3").find("a")["title"]
    price = article.select_one("p.price_color").text.split("£")[1]
    items.append([title, price])

In [73]:
items

[['A Light in the Attic', '51.77'],
 ['Tipping the Velvet', '53.74'],
 ['Soumission', '50.10'],
 ['Sharp Objects', '47.82'],
 ['Sapiens: A Brief History of Humankind', '54.23'],
 ['The Requiem Red', '22.65'],
 ['The Dirty Little Secrets of Getting Your Dream Job', '33.34'],
 ['The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  '17.93'],
 ['The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  '22.60'],
 ['The Black Maria', '52.15'],
 ['Starving Hearts (Triangular Trade Trilogy, #1)', '13.99'],
 ["Shakespeare's Sonnets", '20.66'],
 ['Set Me Free', '17.46'],
 ["Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", '52.29'],
 ['Rip it Up and Start Again', '35.02'],
 ['Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  '57.25'],
 ['Olio', '23.88'],
 ['Mesaerion: The Best Science Fiction Stories 1800-1849', '37.59'],
 ['Libertarianism for Beginners', '51.33'],
 ["It's Only the Himalayas", '45.17']]

In [74]:
import pandas as pd

In [75]:
df = pd.DataFrame(items)

In [76]:
df

                                                    0      1
0                                A Light in the Attic  51.77
1                                  Tipping the Velvet  53.74
2                                          Soumission  50.10
3                                       Sharp Objects  47.82
4               Sapiens: A Brief History of Humankind  54.23
5                                     The Requiem Red  22.65
6   The Dirty Little Secrets of Getting Your Dream...  33.34
7   The Coming Woman: A Novel Based on the Life of...  17.93
8   The Boys in the Boat: Nine Americans and Their...  22.60
9                                     The Black Maria  52.15
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99
11                              Shakespeare's Sonnets  20.66
12                                        Set Me Free  17.46
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29
14                          Rip it Up and Start Again  35.02
15  Our Band Could Be Your Life: Scenes from the A...  57.25
16                                               Olio  23.88
17  Mesaerion: The Best Science Fiction Stories 18...  37.59
18                       Libertarianism for Beginners  51.33
19                            It's Only the Himalayas  45.17

In [89]:
items = []
for article in articles:
    title = article.find("h3").find("a")["title"]
    price = article.select_one("p.price_color").text.split("£")[1]
    rating_elements = article.select_one("p.star-rating")
    rating = rating_elements["class"][1]
    items.append([title, price, rating])

In [90]:
df = pd.DataFrame(items, columns = ["Book title", "Price", "Rating"])

In [91]:
df

                                           Book title  Price Rating
0                                A Light in the Attic  51.77  Three
1                                  Tipping the Velvet  53.74    One
2                                          Soumission  50.10    One
3                                       Sharp Objects  47.82   Four
4               Sapiens: A Brief History of Humankind  54.23   Five
5                                     The Requiem Red  22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  22.60   Four
9                                     The Black Maria  52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99    Two
11                              Shakespeare's Sonnets  20.66   Four
12                                        Set Me Free  17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29   Five
14                          Rip it Up and Start Again  35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  57.25  Three
16                                               Olio  23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  37.59    One
18                       Libertarianism for Beginners  51.33    Two
19                            It's Only the Himalayas  45.17    Two

In [92]:
df.to_csv("bs4_data.csv",index=False)